$(document).ready(function(){
  $("#hide").click(function(){
    $("li").hide();
  });
  $("#show").click(function(){
    $("li").show();
  });
  $("#testing").click(function(){
    $(".test").hide();
  });
  $("#color").click(function(){
    $("li").css("color","blue");
  });
  $("#normal").click(function(){
    $("li").css("color","black");
  });
});
